package enums;

public enum EEvent {

	NEW_RAILS, HOSPITAL_FOUNDING, SECOND_CHANCE, ONE_MORE_DAY, RING_RAILROADS,
	GOVERNMENT_MOBILIZATION, GOOD_SEASON, SHIPS_ARRIVE, OVERSEAS_MIGRATION, PURIFY_WATER,
	TELEGRAPH_MESSAGE, WHEN_THE_PLANS_WERE_GOOD, MAIL_CORRESPODENCE, SCIENCE_TRIUMPH,
	TRAVEL_DAY_AND_NIGHT

}
